### ISSUE TITLE
Depend on PocketMoney

### ISSUE THREAD

**Issue by Julicraft44** [poggit-orphanage/ChestShop#11]
I download the latest version of ChestShop, #19.
 When I put the plugin in my plugins folder and reload the server, the console says, that I need PocketMoney to run the plugin on my server.
So I search for it on the Dev Builds and found 2 PocketMoney plugins. But no plugin works.
Why I can't use the EconomyAPI. Why is the depend on PocketMoney?
Help...

**Comment by jasonwynn10** [comment]
Don't use builds. There is a branch for EconomyAPI as well as the original branch for the legacy plugin code.
