### ISSUE TITLE
Crate are not creating

### ISSUE THREAD

**Issue by dapwestwood** [poggit-orphanage/ChestShop#13]
There is no such errors, crush, etc. I just cant make Cshop i put like the format. Thank youu
![Screenshot_20190728-191952](https://user-images.githubusercontent.com/32587372/62006639-7db3d580-b16d-11e9-82c0-401fe4bb3e41.png)

**Comment by jasonwynn10** [comment]
Fixed in https://github.com/poggit-orphanage/ChestShop/commit/c5adf5933f703e0ab06fb96833b838438ff161cb
