### ISSUE TITLE
The text on the sign is black

### ISSUE THREAD

**Issue by Khuirul-Huda** [poggit-orphanage/ChestShop#24]
Hi, Shouldn't the text on the sign be anything other than black? But why when I create a chestshop, text on the sign is black?
Below is a screenshot of my  members:
![Screenshot_20201008-181827_cropped](https://user-images.githubusercontent.com/67778682/95539619-09372080-0a19-11eb-8048-e91a5889b8ae.png)

I don't really understand this problem.

**Comment by provsalt** [comment]
yo stop being racist to black colored text.

Also literally in the readme the pictures do not contain any color
